application: con
version: ${app_version}
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /static
  static_dir: view/static
  expiration: 30m  # Changes more often

- url: .*
  script: console.py
