application: jhs
version: 1
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /
  static_files: static/console.html
  upload: static/console.html
  expiration: 30m  # Changes more often

- url: /static
  static_dir: static
  expiration: 30m  # Changes more often

- url: .*
  script: console.py
