application: con
version: master
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /console/static
  static_dir: console/app/view/static
  expiration: 30m  # Changes more often

- url: /console.*
  script: console/app/console.py

- url: /
  script: console/app/console.py
