application: jhs
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/console.html
  upload: static/console.html

- url: /static
  static_dir: static

- url: .*
  script: console.py
